# QMK Build Options
#   change to "no" to disable the options, or define them in the Makefile in 
#   the appropriate keymap folder that will get included automatically
#
CONSOLE_ENABLE = no         # Enable debugging console
COMMAND_ENABLE = no         # Commands for debug and configuration
SLEEP_LED_ENABLE = yes      # 
TAP_DANCE_ENABLE = yes 		# Tap Dance skills
UNICODE_ENABLE = no         # Unicode

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif